PACKAGE_NAME="panthor-cix"
PACKAGE_VERSION="7.2.0"

BUILT_MODULE_NAME[0]="panthor"
DEST_MODULE_LOCATION[0]="/updates"
AUTOINSTALL="yes"

MAKE[0]="'make' -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
CLEAN="'make' -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"
