#!/bin/bash
# 32-quadlet-shim.sh — translate /etc/containers/systemd/*.container
# files into native systemd .service units so the agent stack runs
# under Debian Bookworm's podman 4.3 (no Quadlet support — Quadlet
# was added in podman 4.4, no backport in Debian 12 stable or
# bookworm-backports as of 2026-05).
#
# When/if we move to Trixie or backports lands a newer podman, this
# hook becomes a no-op (Quadlet generator handles .container files
# natively and the .service files we emit are harmless duplicates).
#
# Translation rules:
#   [Unit]      → [Unit]
#   [Service]   → fields preserved
#   [Install]   → preserved, default to multi-user.target
#   [Container] → translated to ExecStart `podman run` flags:
#       Image=...           → image arg (positional last)
#       ContainerName=NAME  → --name=NAME --replace --rm
#       Entrypoint=...      → --entrypoint=...
#       Exec=...            → command appended after image
#       EnvironmentFile=... → --env-file=...
#       Volume=src:dst:OPT  → -v src:dst:OPT
#       PublishPort=h:c     → -p h:c
#       Network=...         → --network=...
#       AutoUpdate=registry → IGNORED (we pin digests anyway)
#   [Network]   → translated to ExecStart `podman network create`
#       NetworkName=NAME    → name positional
#       IPv6=...            → --ipv6
#       Internal=true/false → --internal
#       Subnet=...          → --subnet=...
set -euo pipefail

echo "[32] quadlet → .service shim (podman 4.3 compatibility)"

QDIR=/etc/containers/systemd
SDIR=/etc/systemd/system
[ -d "$QDIR" ] || { echo "    no quadlet dir; skipping"; exit 0; }

translate_container() {
    local f="$1"
    local name unit_block service_block install_block image entrypoint exec env_files volumes ports networks container_name
    name=$(basename "$f" .container)

    # Carve into [Unit] / [Container] / [Service] / [Install] sections
    unit_block=$(awk '/^\[Unit\]/,/^\[/{if(!/^\[Unit\]/&&/^\[/)exit; if(!/^\[Unit\]/)print}' "$f")
    service_block=$(awk '/^\[Service\]/,/^\[/{if(!/^\[Service\]/&&/^\[/)exit; if(!/^\[Service\]/)print}' "$f")
    install_block=$(awk '/^\[Install\]/,/^\[/{if(!/^\[Install\]/&&/^\[/)exit; if(!/^\[Install\]/)print}' "$f")

    # Extract Container fields
    image=$(awk '/^\[Container\]/,/^\[/{print}' "$f" | awk -F= '/^Image=/{$1=""; sub(/^=/,""); print; exit}')
    entrypoint=$(awk '/^\[Container\]/,/^\[/{print}' "$f" | awk -F= '/^Entrypoint=/{$1=""; sub(/^=/,""); print; exit}')
    exec_cmd=$(awk '/^\[Container\]/,/^\[/{print}' "$f" | awk -F= '/^Exec=/{$1=""; sub(/^=/,""); print; exit}')
    container_name=$(awk '/^\[Container\]/,/^\[/{print}' "$f" | awk -F= '/^ContainerName=/{$1=""; sub(/^=/,""); print; exit}')
    [ -z "$container_name" ] && container_name="$name"

    # Multi-value fields: collect all Volume=, PublishPort=, EnvironmentFile=, Network= lines
    env_files=$(awk '/^\[Container\]/,/^\[/{if(/^EnvironmentFile=/){sub(/^EnvironmentFile=/,""); print "--env-file="$0}}' "$f" | tr '\n' ' ')
    volumes=$(awk '/^\[Container\]/,/^\[/{if(/^Volume=/){sub(/^Volume=/,""); print "-v " $0}}' "$f" | tr '\n' ' ')
    ports=$(awk '/^\[Container\]/,/^\[/{if(/^PublishPort=/){sub(/^PublishPort=/,""); print "-p " $0}}' "$f" | tr '\n' ' ')
    networks=$(awk '/^\[Container\]/,/^\[/{if(/^Network=/){sub(/^Network=/,""); print "--network=" $0}}' "$f" | tr '\n' ' ')

    # Build podman run cmdline
    local podman_args="--name=$container_name --replace --rm"
    [ -n "$entrypoint" ] && podman_args="$podman_args --entrypoint=$entrypoint"
    podman_args="$podman_args $env_files $volumes $ports $networks"

    # Compose .service file
    cat > "$SDIR/${name}.service" <<EOF
# Generated by 32-quadlet-shim.sh from $f
# Source-of-truth is $f; if you edit this file, regenerate by re-running
# the post-install hook. Will be replaced by Quadlet when podman 4.4+
# is available.
[Unit]
$unit_block

[Service]
Type=simple
TimeoutStartSec=$(echo "$service_block" | awk -F= '/^TimeoutStartSec=/{print $2; exit}')
$(echo "$service_block" | grep -E '^(Restart|RestartSec|WorkingDirectory|UMask|User|Group|Environment)=' || true)
ExecStartPre=-/usr/bin/podman stop --ignore --time=10 $container_name
ExecStartPre=-/usr/bin/podman rm --ignore --force $container_name
ExecStart=/usr/bin/podman run $podman_args $image $exec_cmd
ExecStop=/usr/bin/podman stop --time=30 $container_name

[Install]
${install_block:-WantedBy=multi-user.target}
EOF

    echo "    wrote $SDIR/${name}.service from $f"
}

translate_network() {
    local f="$1"
    local name network_name subnet ipv6 internal
    name=$(basename "$f" .network)
    network_name=$(awk '/^\[Network\]/,/^\[/{if(/^NetworkName=/){sub(/^NetworkName=/,""); print; exit}}' "$f")
    [ -z "$network_name" ] && network_name="$name"
    subnet=$(awk '/^\[Network\]/,/^\[/{if(/^Subnet=/){sub(/^Subnet=/,""); print; exit}}' "$f")
    ipv6=$(awk '/^\[Network\]/,/^\[/{if(/^IPv6=/){sub(/^IPv6=/,""); print; exit}}' "$f")
    internal=$(awk '/^\[Network\]/,/^\[/{if(/^Internal=/){sub(/^Internal=/,""); print; exit}}' "$f")

    local args=""
    [ "$ipv6" = "true" ] && args="$args --ipv6"
    [ "$internal" = "true" ] && args="$args --internal"
    [ -n "$subnet" ] && args="$args --subnet=$subnet"

    cat > "$SDIR/${name}-network.service" <<EOF
[Unit]
Description=podman network ${network_name}
After=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/sh -c '/usr/bin/podman network exists $network_name || /usr/bin/podman network create $args $network_name'
ExecStop=/usr/bin/podman network rm --force $network_name

[Install]
WantedBy=multi-user.target
EOF
    echo "    wrote $SDIR/${name}-network.service from $f"
}

# Translate every .container + .network file
for f in "$QDIR"/*.container; do
    [ -f "$f" ] || continue
    translate_container "$f"
done
for f in "$QDIR"/*.network; do
    [ -f "$f" ] || continue
    translate_network "$f"
done

# daemon-reload — best-effort in chroot, definitive on first boot
systemctl daemon-reload || true

# Enable each agent service for boot
for svc in "$SDIR"/*-network.service "$SDIR"/zeroclaw.service "$SDIR"/openclaw.service "$SDIR"/hermes.service; do
    [ -f "$svc" ] || continue
    name=$(basename "$svc")
    systemctl enable "$name" 2>&1 | tail -2 || true
done

echo ""
echo "Generated agent .service units:"
ls -la "$SDIR"/{zeroclaw,openclaw,hermes,hermes-isolated-network}.service 2>/dev/null || true
