#!/bin/bash
# 32-quadlet-shim.sh — translate /etc/containers/systemd/*.{container,network}
# files into native systemd .service units so the agent stack runs
# under Debian Bookworm's podman 4.3 (no Quadlet support — Quadlet
# was added in podman 4.4, no backport in Debian 12 stable or
# bookworm-backports as of 2026-05).
#
# When/if we move to Trixie or backports lands a newer podman, this
# hook becomes a no-op (Quadlet generator handles .container files
# natively and the .service files we emit are harmless duplicates).
set -euo pipefail

echo "[32] quadlet → .service shim (podman 4.3 compatibility)"

QDIR=/etc/containers/systemd
SDIR=/etc/systemd/system
[ -d "$QDIR" ] || { echo "    no quadlet dir; skipping"; exit 0; }

# ----------------------------------------------------------------------
# Section extractor — prints the lines BETWEEN [SectionName] and the
# next [.../] header (exclusive). Robust to blank lines and comments.
# ----------------------------------------------------------------------
section() {
    local file="$1" name="$2"
    awk -v want="[$name]" '
        BEGIN { in_sec = 0 }
        /^\[/ { in_sec = ($0 == want); next }
        in_sec { print }
    ' "$file"
}

# Extract a single Key=value line from a section. Returns empty if absent.
single() {
    local file="$1" name="$2" key="$3"
    section "$file" "$name" | awk -F= -v k="$key" '$1 == k { sub(/^[^=]*=/, ""); print; exit }'
}

# Extract all values of a repeating Key= within a section.
multi() {
    local file="$1" name="$2" key="$3"
    section "$file" "$name" | awk -F= -v k="$key" '$1 == k { sub(/^[^=]*=/, ""); print }'
}

translate_container() {
    local f="$1" name container_name image entrypoint exec_cmd
    name=$(basename "$f" .container)

    image=$(single "$f" Container Image)
    entrypoint=$(single "$f" Container Entrypoint)
    exec_cmd=$(single "$f" Container Exec)
    container_name=$(single "$f" Container ContainerName)
    [ -z "$container_name" ] && container_name="$name"

    # Build podman run cmdline
    local args="--name=$container_name --replace --rm"
    [ -n "$entrypoint" ] && args="$args --entrypoint=$entrypoint"

    while read -r v; do [ -n "$v" ] && args="$args --env-file=$v"; done < <(multi "$f" Container EnvironmentFile)
    while read -r v; do [ -n "$v" ] && args="$args -v $v"; done < <(multi "$f" Container Volume)
    while read -r v; do [ -n "$v" ] && args="$args -p $v"; done < <(multi "$f" Container PublishPort)
    while read -r v; do [ -n "$v" ] && args="$args --network=$v"; done < <(multi "$f" Container Network)

    # Carve [Unit] / [Service] / [Install] sections (preserve as-is)
    local unit_block service_block install_block
    unit_block=$(section "$f" Unit)
    service_block=$(section "$f" Service)
    install_block=$(section "$f" Install)
    [ -z "$install_block" ] && install_block="WantedBy=multi-user.target"

    # Filter Service block to only Service-relevant fields with NON-
    # EMPTY values (preserve TimeoutStartSec, Restart*, User, Group,
    # WorkingDirectory, UMask, Environment). Empty values would cause
    # systemd to warn "Failed to parse Foo= parameter, ignoring".
    local svc_kept
    svc_kept=$(echo "$service_block" | awk -F= '
        /^(TimeoutStartSec|Restart|RestartSec|User|Group|WorkingDirectory|UMask|Environment)=/ {
            sub(/^[^=]*=/, "", $0)
            gsub(/^[ \t]+|[ \t]+$/, "", $0)
            if (length($0) > 0) print
        }
        # Re-print with the key+= prefix
    ' || true)
    # The awk above strips both sides; redo to keep key=value
    svc_kept=$(echo "$service_block" | awk '
        /^(TimeoutStartSec|Restart|RestartSec|User|Group|WorkingDirectory|UMask|Environment)=/ {
            split($0, kv, "=")
            val = $0
            sub(/^[^=]*=/, "", val)
            gsub(/^[ \t]+|[ \t]+$/, "", val)
            if (length(val) > 0) print kv[1] "=" val
        }
    ' || true)

    {
        echo "# Generated by 32-quadlet-shim.sh from $f"
        echo "# Source-of-truth: $f. Re-run the hook after editing the .container."
        echo "# Will be supersedeable by Quadlet once podman 4.4+ ships."
        echo ""
        echo "[Unit]"
        echo "$unit_block"
        echo ""
        echo "[Service]"
        echo "Type=simple"
        [ -n "$svc_kept" ] && echo "$svc_kept"
        echo "ExecStartPre=-/usr/bin/podman stop --ignore --time=10 $container_name"
        echo "ExecStartPre=-/usr/bin/podman rm --ignore --force $container_name"
        echo "ExecStart=/usr/bin/podman run $args $image ${exec_cmd:-}"
        echo "ExecStop=/usr/bin/podman stop --time=30 $container_name"
        echo ""
        echo "[Install]"
        echo "$install_block"
    } > "$SDIR/${name}.service"
    echo "    wrote $SDIR/${name}.service"
}

translate_network() {
    local f="$1" name network_name subnet ipv6 internal
    name=$(basename "$f" .network)
    network_name=$(single "$f" Network NetworkName)
    [ -z "$network_name" ] && network_name="$name"
    subnet=$(single "$f" Network Subnet)
    ipv6=$(single "$f" Network IPv6)
    internal=$(single "$f" Network Internal)

    local netargs=""
    [ "$ipv6" = "true" ] && netargs="$netargs --ipv6"
    [ "$internal" = "true" ] && netargs="$netargs --internal"
    [ -n "$subnet" ] && netargs="$netargs --subnet=$subnet"

    cat > "$SDIR/${name}-network.service" <<EOF
# Generated by 32-quadlet-shim.sh from $f
[Unit]
Description=podman network $network_name
After=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/sh -c '/usr/bin/podman network exists $network_name || /usr/bin/podman network create $netargs $network_name'
ExecStop=/usr/bin/podman network rm --force $network_name

[Install]
WantedBy=multi-user.target
EOF
    echo "    wrote $SDIR/${name}-network.service"
}

# Translate every .container + .network file in the quadlet dir
for f in "$QDIR"/*.container; do
    [ -f "$f" ] || continue
    translate_container "$f"
done
for f in "$QDIR"/*.network; do
    [ -f "$f" ] || continue
    translate_network "$f"
done

systemctl daemon-reload || true

# Enable each generated service for boot. Networks first so containers
# referencing them find them at startup.
for svc in "$SDIR"/*-network.service; do
    [ -f "$svc" ] || continue
    systemctl enable "$(basename "$svc")" 2>&1 | tail -1 || true
done
for name in zeroclaw openclaw hermes; do
    [ -f "$SDIR/${name}.service" ] || continue
    systemctl enable "${name}.service" 2>&1 | tail -1 || true
done

echo ""
echo "Final agent .service units:"
ls -la "$SDIR"/{zeroclaw,openclaw,hermes,hermes-isolated-network}.service 2>/dev/null || true
