#!/bin/bash
# 34-fstab.sh - write /etc/fstab post-install.
#
# Discovered 2026-05-05 (r62 diagnostic): /etc/fstab on the installed system
# was EMPTY despite partman having allegedly written it. /boot/efi was not
# mounted at boot, so systemd-boot's loader entries (correctly written to the
# ESP by 70-bootloader.sh) were invisible to bootctl + the running system -
# and any future kernel update would write to the wrong place.
#
# Root cause is unclear (possibly the rootfs.tar.zst step in our extract
# pipeline overwrites /etc/fstab with an empty file from the source tar).
# Either way, defensive hook: derive ROOT + ESP UUIDs from blkid and
# write a known-good /etc/fstab if it's empty or missing both lines.
set -euo pipefail

echo "[34] /etc/fstab generation"

if [ -s /etc/fstab ] && grep -Eq "[[:space:]]/boot/efi[[:space:]]" /etc/fstab && grep -Eq "[[:space:]]/[[:space:]]" /etc/fstab; then
    echo "  /etc/fstab already has root + ESP entries - leaving alone"
    exit 0
fi

find_mount_source() {
    local target=$1
    findmnt -nro SOURCE,TARGET 2>/dev/null | awk -v t="$target" '$2 == t {print $1; exit}' || true
}

find_mount_fstype() {
    local target=$1
    findmnt -nro FSTYPE,TARGET 2>/dev/null | awk -v t="$target" '$2 == t {print $1; exit}' || true
}

uuid_for() {
    local label=$1
    local dev=$2
    local uuid

    if [ -z "$dev" ]; then
        echo "  ERROR: could not find device for $label" >&2
        return 1
    fi

    uuid=$(blkid -s UUID -o value "$dev" 2>/dev/null || true)
    if [ -z "$uuid" ]; then
        echo "  ERROR: could not derive UUID for $label ($dev)" >&2
        return 1
    fi

    printf "%s" "$uuid"
}

# Derive UUIDs from the running mounts. We run inside chroot via in-target, so
# /proc/mounts shows the target mount table.
ROOT_DEV=$(find_mount_source /)
ROOT_FSTYPE=$(find_mount_fstype /)
ROOT_FSTYPE=${ROOT_FSTYPE:-ext4}

ESP_DEV=$(find_mount_source /boot/efi)

# Fallback for cases where /boot/efi is not still mounted in the chroot: use the
# first vfat partition on the same parent disk as root.
ROOT_PARENT=$(lsblk -no PKNAME "$ROOT_DEV" 2>/dev/null | sed -n '1p' || true)
if [ -z "$ESP_DEV" ] && [ -n "$ROOT_PARENT" ]; then
    while read -r name fstype; do
        if [ "$fstype" = "vfat" ]; then
            ESP_DEV="/dev/$name"
            break
        fi
    done < <(lsblk -lno NAME,FSTYPE "/dev/$ROOT_PARENT" 2>/dev/null || true)
fi

BOOT_DEV=$(find_mount_source /boot)
BOOT_FSTYPE=$(find_mount_fstype /boot)
BOOT_FSTYPE=${BOOT_FSTYPE:-ext4}
if [ "$BOOT_DEV" = "$ROOT_DEV" ]; then
    BOOT_DEV=""
fi

ROOT_UUID=$(uuid_for root "$ROOT_DEV")
ESP_UUID=$(uuid_for /boot/efi "$ESP_DEV")

BOOT_UUID=""
if [ -n "$BOOT_DEV" ]; then
    BOOT_UUID=$(uuid_for /boot "$BOOT_DEV")
fi

SWAP_DEVS=$(swapon --noheadings --raw --show=NAME 2>/dev/null || true)
if [ -z "$SWAP_DEVS" ] && [ -n "$ROOT_PARENT" ]; then
    SWAP_DEVS=$(lsblk -lno NAME,FSTYPE "/dev/$ROOT_PARENT" 2>/dev/null | awk '$2 == "swap" {print "/dev/"$1}' || true)
fi

FSTAB_TMP=/etc/fstab.cix-installer.$$
{
    echo "# /etc/fstab - generated by NCZ 26.6 cix-installer (34-fstab.sh)"
    echo "# <fs>            <mountpoint>  <type>  <opts>             <dump> <pass>"
    printf "UUID=%s  /             %s    errors=remount-ro  0      1\n" "$ROOT_UUID" "$ROOT_FSTYPE"
    if [ -n "$BOOT_UUID" ]; then
        printf "UUID=%s  /boot         %s    defaults           0      2\n" "$BOOT_UUID" "$BOOT_FSTYPE"
    fi
    printf "UUID=%s  /boot/efi     vfat    defaults,umask=0077 0      2\n" "$ESP_UUID"
    for swap_dev in $SWAP_DEVS; do
        swap_uuid=$(uuid_for swap "$swap_dev")
        printf "UUID=%s  none          swap    sw                0      0\n" "$swap_uuid"
    done
} > "$FSTAB_TMP"

install -m 0644 "$FSTAB_TMP" /etc/fstab
rm -f "$FSTAB_TMP"

echo "  /etc/fstab written:"
cat /etc/fstab | sed 's/^/    /'
