#!/bin/bash
# 34-fstab.sh — write /etc/fstab post-install.
#
# Discovered 2026-05-05 (r62 diagnostic): /etc/fstab on the installed system
# was EMPTY despite partman having allegedly written it. /boot/efi was not
# mounted at boot, so systemd-boot's loader entries (correctly written to the
# ESP by 70-bootloader.sh) were invisible to bootctl + the running system —
# and any future kernel update would write to the wrong place.
#
# Root cause is unclear (possibly the rootfs.tar.zst step in our extract
# pipeline overwrites /etc/fstab with an empty file from the source tar).
# Either way, defensive hook: derive ROOT + ESP UUIDs from blkid and
# write a known-good /etc/fstab if it's empty or missing both lines.
set +e

echo "[34] /etc/fstab generation"

if [ -s /etc/fstab ] && grep -q "/boot/efi" /etc/fstab && grep -q " / " /etc/fstab; then
    echo "  /etc/fstab already has root + ESP entries — leaving alone"
    exit 0
fi

# Derive UUIDs from the running mounts (we're inside chroot via in-target,
# so /proc/mounts shows the target's mount table)
ROOT_DEV=$(findmnt -no SOURCE / 2>/dev/null)
ESP_DEV=""
# ESP candidates: any vfat partition on the same parent disk as root
ROOT_PARENT=$(lsblk -no PKNAME "$ROOT_DEV" 2>/dev/null | head -1)
if [ -n "$ROOT_PARENT" ]; then
    for p in $(lsblk -lno NAME,FSTYPE "/dev/$ROOT_PARENT" 2>/dev/null | awk '$2 == "vfat" {print "/dev/"$1}'); do
        ESP_DEV="$p"
        break
    done
fi

ROOT_UUID=$(blkid -s UUID -o value "$ROOT_DEV" 2>/dev/null)
ESP_UUID=$(blkid -s UUID -o value "$ESP_DEV" 2>/dev/null)

if [ -z "$ROOT_UUID" ] || [ -z "$ESP_UUID" ]; then
    echo "  ERROR: could not derive UUIDs (ROOT=$ROOT_DEV/$ROOT_UUID ESP=$ESP_DEV/$ESP_UUID)"
    echo "  /etc/fstab left as-is — system may not mount /boot/efi at boot!"
    exit 0
fi

cat > /etc/fstab <<FSTAB_FILE
# /etc/fstab — generated by NCZ 26.5 cix-installer (34-fstab.sh)
# <fs>            <mountpoint>  <type>  <opts>             <dump> <pass>
UUID=$ROOT_UUID  /             ext4    errors=remount-ro  0      1
UUID=$ESP_UUID  /boot/efi     vfat    defaults,umask=0077 0      2
FSTAB_FILE

echo "  /etc/fstab written:"
cat /etc/fstab | sed 's/^/    /'
