#!/bin/bash
# 60-plymouth.sh — Plymouth boot splash with nclawzero branding.
#
# Replaces the bare-text kernel boot output with a graphical splash
# (the "multicolor pretty boot" other distros have). Uses the `spinner`
# theme as a base and overlays our wordmark. Themes get more polish in
# follow-up commits — this is the v0 "looks intentional".
set -euo pipefail

echo "[60] Plymouth boot splash"

DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    plymouth plymouth-themes

# Use the spinner theme as the closest "modern subtle" base; we'll
# replace the logo bitmap with nclawzero wordmark in a follow-up.
plymouth-set-default-theme -R spinner || true

# Make sure the kernel cmdline has `splash quiet` so plymouth has a
# chance to render. systemd-boot's loader entry is generated by
# 70-bootloader.sh and reads /etc/default/grub style or /etc/cmdline,
# so we drop a marker file here that 70 picks up.
cat > /etc/kernel/cmdline.d/10-splash.conf <<'EOF'
splash quiet
EOF
mkdir -p /etc/kernel/cmdline.d
