#!/bin/bash
# 80-npu.sh — install NCZ NPU stack for Cix Sky1 / Zhouyi v3
#
# Source: FyrbyAdditive/ms-r1-npu-hack (BSD-2-Clause-Patent)
#   + cixtech/cix_opensource__release__npu_driver branch cix_mainline_dev
#
# Four MS-R1 fixes applied in the kernel module:
#   1. ACPI SSDT override: _HID="CIXH4010" on NPU cores (missing in shipped BIOS)
#   2. v0-compat ioctl handlers: translates cix-noe-umd 2.0.x struct layouts
#   3. SMMU 32-bit constraint: forces bus_dma_limit=0xc0000000, dma_mask=32
#   4. asid_base[4]->asid_base[32] widening for QUERY_CAP UMD ABI compat
#
# Result: mobilenet_v2.cix runs at ~640 inf/s (1.5ms avg) via cix-noe-umd 2.0.2
#
# RUNS INSIDE CHROOT (via run-all.sh). All paths are relative to the
# installed system root (no /target/ prefix).
#
# Ordering: this hook runs before 70-bootloader.sh (which fires on EXIT trap).
# Sequence:
#   1. install .ko into /usr/lib/modules/$KVER/extra/
#   2. depmod -a $KVER
#   3. ensure /boot/initrd.img-$KVER exists (normally generated by 10-our-kernel.sh)
#   4. prepend npu-acpi-override.cpio to /boot/initrd.img-$KVER
#   5. configure modules-load.d
# Then 70-bootloader.sh stages /boot/initrd.img-$KVER → /boot/efi/initrd.img-$KVER
# and adds `initrd /initrd.img-$KVER` to the systemd-boot loader entries.

set +e

INSTALLER_META=/usr/local/lib/cix-installer
ASSETS=/usr/local/lib/cix-installer/assets/npu
if [ ! -d "$ASSETS" ] && [ -d /cdrom/cixmini/assets/npu ]; then
    ASSETS=/cdrom/cixmini/assets/npu
fi
SSDT_CPIO="$ASSETS/npu-acpi-override.cpio"

KERNEL_LABELS=()
KERNEL_VERS=()
if [ -f "$INSTALLER_META/KVER_LTS" ]; then
    KVER_LTS=$(cat "$INSTALLER_META/KVER_LTS" 2>/dev/null | tr -d ' \t\r\n')
    if [ -n "$KVER_LTS" ]; then
        KERNEL_LABELS+=("lts")
        KERNEL_VERS+=("$KVER_LTS")
    fi
fi
if [ -f "$INSTALLER_META/KVER_NEXT" ]; then
    KVER_NEXT=$(cat "$INSTALLER_META/KVER_NEXT" 2>/dev/null | tr -d ' \t\r\n')
    if [ -n "$KVER_NEXT" ]; then
        KERNEL_LABELS+=("next")
        KERNEL_VERS+=("$KVER_NEXT")
    fi
fi

if [ "${#KERNEL_VERS[@]}" -eq 0 ]; then
    echo "[80] WARN: no KVER_LTS or KVER_NEXT sidecar found; skipping kernel-specific NPU setup"
fi
if [ ! -d "$ASSETS" ]; then
    echo "[80] WARN: NPU asset directory missing at $ASSETS"
fi

echo "[80] installing NCZ NPU stack (FyrbyAdditive MS-R1 fixes)..."

# --- Step 1: install kernel modules ---
# Two supported sources, in priority order:
#   1. In-tree module shipped inside modules-cixmini.tgz (CONFIG_ARMCHINA_NPU=m).
#      This is the case for the NEXT kernel (7.0.x-cix-sky1-next) where the
#      driver is built as part of the kernel and already carries the correct
#      vermagic. Nothing to copy — just confirm + depmod.
#   2. Out-of-tree prebuilt $ASSETS/armchina_npu-${KVER}.ko, whose vermagic MUST
#      exactly match $KVER. This is the case for the LTS kernel
#      (6.18.26-ncz-lts), whose config does NOT enable CONFIG_ARMCHINA_NPU.
for i in "${!KERNEL_VERS[@]}"; do
    LABEL="${KERNEL_LABELS[$i]}"
    KVER="${KERNEL_VERS[$i]}"
    if [ ! -d "/usr/lib/modules/$KVER" ]; then
        echo "[80] WARN: /usr/lib/modules/$KVER does not exist; skipping $KVER"
        continue
    fi

    INTREE=$(find "/usr/lib/modules/$KVER/kernel" -name 'armchina_npu.ko*' 2>/dev/null | head -1)
    SRC="$ASSETS/armchina_npu-${KVER}.ko"

    if [ -n "$INTREE" ]; then
        # In-tree build (NEXT): driver already present with matching vermagic.
        depmod -a "$KVER" 2>/dev/null
        echo "[80] $LABEL/$KVER: using in-tree armchina_npu.ko ($INTREE)"
    elif [ -f "$SRC" ]; then
        # Guard: refuse to install a vermagic-mismatched OOT module — loading it
        # would either be rejected by modprobe or (with MODVERSIONS off) risk a
        # silent ABI mismatch. Skip loudly instead.
        VM=$(modinfo -F vermagic "$SRC" 2>/dev/null | awk '{print $1}')
        if [ -n "$VM" ] && [ "$VM" != "$KVER" ]; then
            echo "[80] ERROR: $SRC vermagic '$VM' != kernel '$KVER'; refusing to install (rebuild OOT module for $KVER)"
            continue
        fi
        install -D -m 0644 "$SRC" "/usr/lib/modules/$KVER/extra/armchina_npu.ko"
        depmod -a "$KVER" 2>/dev/null
        echo "[80] $LABEL/$KVER: installed OOT armchina_npu.ko (vermagic $VM)"
    else
        echo "[80] WARN: no in-tree module and no $SRC; NPU unavailable for $LABEL/$KVER"
    fi

    # --- Overlay override (NCZ validated fixes, r104) ---
    # The in-tree armchina_npu.ko in modules-cixmini.tgz may predate the
    # ARCH_V3=y + iova_region=2 fixes (Zhouyi V3 detection / 32-bit-bus IOVA
    # cap). A validated overlay installed to updates/ takes depmod precedence
    # over kernel/, so the correct module loads even on an unrebuilt kernel.
    OVERLAY=""
    for cand in \
        "/usr/local/lib/cix-installer/assets/kernel/modules-overlay/$KVER/armchina_npu.ko" \
        "/cdrom/cixmini/assets/kernel/modules-overlay/$KVER/armchina_npu.ko"; do
        [ -f "$cand" ] && { OVERLAY="$cand"; break; }
    done
    if [ -n "$OVERLAY" ]; then
        OVM=$(modinfo -F vermagic "$OVERLAY" 2>/dev/null | awk '{print $1}')
        if [ -n "$OVM" ] && [ "$OVM" != "$KVER" ]; then
            echo "[80] WARN: overlay $OVERLAY vermagic '$OVM' != '$KVER'; not applying"
        else
            install -D -m 0644 "$OVERLAY" "/usr/lib/modules/$KVER/updates/armchina_npu.ko"
            depmod -a "$KVER" 2>/dev/null
            echo "[80] $LABEL/$KVER: applied validated NPU overlay (ARCH_V3+iova=2, vermagic $OVM) -> updates/"
        fi
    fi
done

# --- Step 2: ensure initrd exists for each NCZ kernel ---
# 10-our-kernel.sh now generates initrds in the required phase. Keep this
# fallback for older/rerun targets, but the boot-critical path no longer
# depends on this optional hook.
for KVER in "${KERNEL_VERS[@]}"; do
    if [ -d "/usr/lib/modules/$KVER" ]; then
        if [ ! -f "/boot/initrd.img-$KVER" ]; then
            echo "[80] generating initrd for $KVER..."
            update-initramfs -c -k "$KVER" 2>&1 | tail -5
        else
            echo "[80] initrd already present for $KVER"
        fi
    fi
done

# --- Step 3: ACPI SSDT override — BOARD-GATED (r123) ---
#
# The SSDT injects _HID="CIXH4010" onto the NPU compute cores (CRE0/CRE1/CRE2).
# This is a fix for ONE specific defect: the Minisforum MS-R1's shipped BIOS
# omits that _HID, so the cores never enumerate (CIXH4000:00 appears but no
# CIXH4010:0x). On boards whose firmware is correct — Radxa Orion O6 / O6N —
# the cores enumerate natively, and force-loading a second SSDT that redefines
# the same ACPI named objects risks an AML name-collision (AE_ALREADY_EXISTS).
# So we only prepend the override when the target actually needs it.
#
# Detection priority (runs in the d-i chroot, where /proc /sys /dev are
# bind-mounted, so it reflects the REAL hardware being installed):
#   0. operator override  /usr/local/lib/cix-installer/NPU_SSDT = force|skip
#   1. functional ACPI check (authoritative, board-agnostic):
#        >=3 CIXH4010:* cores present -> enumerate natively   -> SKIP
#        CIXH4000:00 present, <3 cores -> MS-R1-class bug      -> APPLY
#   2. DMI board match (only if ACPI gives no signal):
#        MS-R1 / MINISFORUM -> APPLY ;  Radxa / Orion -> SKIP
#   3. unknown + no CIX NPU ACPI signal -> SKIP + warn (refuse to inject an
#        MS-R1 SSDT into unidentified hardware; a real MS-R1 would have matched
#        step 1 or the MINISFORUM DMI rule). Override with NPU_SSDT=force.
should_apply_npu_ssdt() {
    local force="$INSTALLER_META/NPU_SSDT"
    if [ -f "$force" ]; then
        case "$(tr -d ' \t\r\n' < "$force" 2>/dev/null)" in
            force|apply|on|1) echo "[80] NPU SSDT: forced ON by $force"; return 0 ;;
            skip|off|0)       echo "[80] NPU SSDT: forced OFF by $force"; return 1 ;;
        esac
    fi

    if [ -d /sys/bus/acpi/devices ]; then
        # r124: require the FULL complement of cores before declaring firmware OK.
        # A partial enumeration (1-2 of 3) is still a defect we should fix, so
        # only >=3 CIXH4010:* cores count as "native".
        local ncores
        ncores=$(ls -d /sys/bus/acpi/devices/CIXH4010:* 2>/dev/null | wc -l)
        if [ "$ncores" -ge 3 ]; then
            echo "[80] NPU SSDT: $ncores CIXH4010:* cores enumerate natively (>=3) — SKIP (firmware OK; likely O6/O6N)"
            return 1
        fi
        if [ -e /sys/bus/acpi/devices/CIXH4000:00 ]; then
            echo "[80] NPU SSDT: NPU device present, cores incomplete ($ncores/3) — APPLY (MS-R1-class BIOS _HID gap)"
            return 0
        fi
        echo "[80] NPU SSDT: no CIXH4000 in ACPI view — falling back to DMI board match"
    else
        echo "[80] NPU SSDT: /sys/bus/acpi unavailable in chroot — falling back to DMI board match"
    fi

    local pn pf sv
    pn=$(cat /sys/class/dmi/id/product_name   2>/dev/null)
    pf=$(cat /sys/class/dmi/id/product_family 2>/dev/null)
    sv=$(cat /sys/class/dmi/id/sys_vendor     2>/dev/null)
    case "$pn $pf $sv" in
        *MS-R1*|*MINISFORUM*|*[Mm]inisforum*)
            echo "[80] NPU SSDT: DMI='$pn'/'$pf' (Minisforum MS-R1) — APPLY"; return 0 ;;
        *Orion*|*[Rr]adxa*)
            echo "[80] NPU SSDT: DMI='$pn'/'$sv' (Radxa Orion) — SKIP (native _HID expected)"; return 1 ;;
    esac

    # r124: unknown board WITHOUT any CIX NPU ACPI signal -> SKIP, do NOT inject.
    # If this were an MS-R1-class board the functional ACPI check above (or the
    # MINISFORUM DMI match) would have already returned APPLY; reaching here
    # means it is not recognizable CIX hardware, so injecting an MS-R1 SSDT is
    # unsafe. Force it on a genuinely-MS-R1-class board with the override file.
    echo "[80] NPU SSDT: board UNKNOWN (pn='$pn' pf='$pf' sv='$sv') and no CIX NPU ACPI signal — SKIP (refusing to inject MS-R1 SSDT into unidentified hardware)"
    echo "[80]   (force on a known MS-R1-class board with: echo force > $INSTALLER_META/NPU_SSDT)"
    return 1
}

# Prepend the 1024-byte SSDT CPIO archive to each kernel's initrd. The kernel
# reads CPIO archives stacked before the main initramfs; the SSDT injects via
# the ACPI override mechanism before any driver probes.
if [ -f "$SSDT_CPIO" ] && should_apply_npu_ssdt; then
    install -D -m 0644 "$SSDT_CPIO" /boot/npu-acpi-override.cpio
    for KVER in "${KERNEL_VERS[@]}"; do
        INITRD="/boot/initrd.img-$KVER"
        if [ -f "$INITRD" ]; then
            # Idempotent: only prepend if not already prepended (check first 4 bytes).
            # CPIO archives start with "070701" (newc magic) — if initrd starts with
            # those bytes we know it's already been prepended.
            head -c 6 "$INITRD" 2>/dev/null | grep -q '070701' && {
                echo "[80] $INITRD already has SSDT prepended, skipping"
                continue
            }
            cp -n "$INITRD" "${INITRD}.pre-npu-override"
            cat "$SSDT_CPIO" "${INITRD}.pre-npu-override" > "${INITRD}.tmp" \
                && mv "${INITRD}.tmp" "$INITRD" \
                && rm -f "${INITRD}.pre-npu-override" \
                && echo "[80] SSDT override prepended to $INITRD"
        else
            echo "[80] WARN: $INITRD not found after update-initramfs; SSDT skipped for $KVER"
        fi
    done
elif [ ! -f "$SSDT_CPIO" ]; then
    echo "[80] WARN: SSDT CPIO missing at $SSDT_CPIO; NPU cores may not enumerate on MS-R1"
else
    echo "[80] NPU SSDT override staged but NOT applied for this board (see detection above)"
fi

# --- Step 4: auto-load on boot ---
mkdir -p /etc/modules-load.d
cat > /etc/modules-load.d/ncz-npu.conf << 'EOF'
# NCZ 26.6: Cix Sky1 / Zhouyi v3 NPU driver
# Probes CIXH4000:00 (\_SB_.NPU0) + CIXH4010:0[012] (3 cores via SSDT override)
# Creates /dev/aipu chardev; inference via cix-noe-umd 2.0.2
armchina_npu
EOF

# --- Step 5: drop NPU-STATUS.md ---
mkdir -p /usr/share/doc/ncz
cat > /usr/share/doc/ncz/NPU-STATUS.md << 'EOF'
# NCZ 26.6 "Reinhardt" — Cix Sky1 / Zhouyi v3 NPU

## What works

- **Kernel module** `armchina_npu.ko` probes clean on MS-R1 for both NCZ kernels:
  - 7.0.12-cix-sky1-next (default; in-tree CONFIG_ARMCHINA_NPU=m)
  - 6.18.26-ncz-lts (stable fallback; out-of-tree module)
- **ACPI SSDT override** corrects the missing `_HID="CIXH4010"` on NPU cores
  (CRE0/CRE1/CRE2) — a bug in Minisforum's shipped BIOS omitted by the OEM.
  Injected via initramfs CPIO prepend; fully reversible. **Board-gated (r123):**
  applied only when the cores don't enumerate natively (MS-R1); skipped on
  boards whose firmware is correct (Radxa Orion O6 / O6N) to avoid an AML
  name-collision. Auto-detected at install; force with
  `echo force|skip > /usr/local/lib/cix-installer/NPU_SSDT`.
- **v0-compat ioctl handlers** bridge the struct-layout gap between
  `cix-noe-umd 2.0.x` (k6.6 ABI) and the current kernel driver.
- **SMMU 32-bit constraint** forces `bus_dma_limit=0xc0000000` and `dma_mask=32`;
  without this the IOMMU hands out 35-bit IOVAs that the NPU's 32-bit address
  bus truncates, causing SMMU faults on every memory access.
- NPU enumeration after boot:
  ```
  /sys/bus/acpi/devices/CIXH4000:00    (NPU device)
  /sys/bus/acpi/devices/CIXH4010:0[012]  (3 cores)
  /dev/aipu                             (char device)
  ```
- **MobileNet V2 inference: ~640 inf/s (1.5 ms avg)** via `cix-noe-umd 2.0.2`
  + pre-compiled `.cix` models from Cix AI Model Hub.

## Installing the userspace runtime

```bash
# Install cix-noe-umd 2.0.2 (compatible with our v0-compat ioctl layer)
curl -LO https://github.com/radxa-pkg/cix-prebuilt/releases/download/rc3.3-2601/cix-noe-umd_2.0.2_arm64.deb
sudo dpkg -i cix-noe-umd_2.0.2_arm64.deb

# Get pre-compiled .cix models
sudo apt install -y python3-pip python3-numpy python3-pillow git git-lfs
git lfs install
git clone --depth 1 https://www.modelscope.cn/cix/ai_model_hub_25_Q3.git
```

## Running inference

```bash
cd ai_model_hub_25_Q3
git lfs pull --include="models/ComputeVision/Image_Classification/onnx_mobilenet_v2/*"
cd models/ComputeVision/Image_Classification/onnx_mobilenet_v2
python3 run_onnx.py
```

Other available pre-compiled models: YOLOv8n, CLIP ViT-B/32, Whisper, ResNet50,
SDXL-Turbo (see https://modelscope.cn/models/cix/ai_model_hub_25_Q3)

## What's still open

- **LLM on Zhouyi v3.** The Compass NN compiler is static-graph only —
  transformer models with KV-cache / variable sequence length don't compile
  cleanly. This is unsolved by anyone (Cix included). Vision models, audio
  (Whisper), and image-gen all work via the Cix model hub.
- **UMD 4.0.0 compat.** Only `cix-noe-umd 2.0.2` is confirmed working.

## Credits

- **FyrbyAdditive/ms-r1-npu-hack** — identified and fixed all four root causes
  on MS-R1 (Armbian). NCZ integrates their patches into the installer.
- **cixtech/cix_opensource__release__npu_driver** (`cix_mainline_dev`)
- **radxa-pkg/cix-prebuilt** — `cix-noe-umd_2.0.2_arm64.deb`
- **Cix AI Model Hub** on ModelScope — pre-compiled `.cix` inference graphs

## References

- [FyrbyAdditive/ms-r1-npu-hack](https://github.com/FyrbyAdditive/ms-r1-npu-hack)
- [cixtech/cix_opensource__release__npu_driver](https://github.com/cixtech/cix_opensource__release__npu_driver)
- [radxa-pkg/cix-prebuilt](https://github.com/radxa-pkg/cix-prebuilt)
- [Cix AI Model Hub](https://www.modelscope.cn/cix/ai_model_hub_25_Q3)
EOF
chmod 0644 /usr/share/doc/ncz/NPU-STATUS.md

# --- Step 5b: install the bundled operator docs (NPU embeddings, inference
# limits/capability matrix, ModelScope model-pull guide). These are baked from
# the repo docs/ via assets/docs/ (symlinks dereferenced at build time), so the
# installed appliance carries the same reference material the repo ships. ---
DOCS_SRC=/usr/local/lib/cix-installer/assets/docs
if [ -d "$DOCS_SRC" ]; then
    for d in "$DOCS_SRC"/*.md; do
        [ -e "$d" ] || continue
        install -m 0644 "$d" /usr/share/doc/ncz/ && \
            echo "[80] doc: /usr/share/doc/ncz/$(basename "$d")"
    done
else
    echo "[80] WARN: $DOCS_SRC not staged - operator docs not installed"
fi


# Marker for 70-bootloader.sh: NPU initrds need staging
mkdir -p /var/lib/ncz
: > /var/lib/ncz/npu-initrd-staging.list
for KVER in "${KERNEL_VERS[@]}"; do
    [ -f "/boot/initrd.img-$KVER" ] && echo "$KVER" >> /var/lib/ncz/npu-initrd-staging.list
done

echo "[80] NPU stack installed: modules + SSDT override + autoload + status doc"
echo "[80] Install cix-noe-umd 2.0.2 from radxa-pkg/cix-prebuilt to enable inference"
